*&---------------------------------------------------------------------*
*& Report ZGER_ALV_011_HOME_S01E09
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZGER_ALV_011_HOME_S01E09.

TYPE-POOLS: SLIS.
TABLES: KNA1, KNVV, T005T.

DATA GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.
TYPES: BEGIN OF TY_OUTTAB,
         INCLUDE TYPE ZGER_011_HOME09_1. " A meglévő struktúra mezői
       TYPES:COLOR TYPE LVC_T_SCOL,         " Színezéshez szükséges mező
       END OF TY_OUTTAB.

DATA: GT_OUTTAB TYPE TABLE OF TY_OUTTAB,
      LS_OUTTAB TYPE TY_OUTTAB.
"DATA GT_OUTTAB TYPE TABLE OF ZGER_011_HOME09_1.
DATA GT_OUTTAB2 TYPE TABLE OF ZGER_011_HOME09_2.
"DATA LS_OUTTAB TYPE ZGER_011_HOME09_1.
DATA LS_OUTTAB2 TYPE ZGER_011_HOME09_2.

DATA G_REPID TYPE SY-REPID.

DATA G_USER_COMMAND TYPE SLIS_FORMNAME VALUE 'USER-COMMAND'.
DATA LAYOUT TYPE SLIS_LAYOUT_ALV.
DATA G_STATUS TYPE SLIS_FORMNAME VALUE 'SET_STATUS'.

" Szelekciós opciók
SELECTION-SCREEN BEGIN OF BLOCK sel WITH FRAME TITLE TEXT-001.
  PARAMETERS P_LAND1 TYPE KNA1-LAND1 DEFAULT 'DE'.
  SELECT-OPTIONS: SO_KUNNR FOR KNA1-KUNNR DEFAULT '0000000099' TO '0000001200',
                  SO_NAME1 FOR KNA1-NAME1,
                  SO_PSTLZ FOR KNA1-PSTLZ,
                  SO_VKORG FOR KNVV-VKORG.
SELECTION-SCREEN END OF BLOCK sel.

SELECTION-SCREEN BEGIN OF BLOCK se2 WITH FRAME TITLE TEXT-002.
  PARAMETERS: P_SZINEZ AS CHECKBOX DEFAULT ''.
SELECTION-SCREEN END OF BLOCK se2.

INITIALIZATION. "mezőkatalógus inicializálása.
  G_REPID = SY-REPID.

START-OF-SELECTION.
  PERFORM FETCH_DATA_KNA1_T005T USING GT_OUTTAB.
  PERFORM FETCH_DATA_KNA1_KNVV USING GT_OUTTAB2.
  PERFORM CALCULATE_VEVO_NR USING GT_OUTTAB.
  PERFORM CALCULATE_VKORG_NR.                                  .
  PERFORM FIELDCAT_INIT USING GT_FIELDCAT[].

END-OF-SELECTION.

IF P_SZINEZ EQ 'X'.
  LAYOUT-INFO_FIELDNAME = 'COLOR'.
ENDIF.


*megjelenítés
CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
        I_CALLBACK_PROGRAM = G_REPID
        IT_FIELDCAT = GT_FIELDCAT[]
        I_SAVE = 'A'
        IS_LAYOUT = LAYOUT
        I_CALLBACK_USER_COMMAND = 'USER_COMMAND'
        I_CALLBACK_PF_STATUS_SET = G_STATUS
        I_BYPASSING_BUFFER = 'X'
    TABLES
        T_OUTTAB = GT_OUTTAB.


FORM SET_STATUS USING rt_extab TYPE slis_t_extab.
  SET PF-STATUS 'ALV'.
ENDFORM.

FORM FIELDCAT_INIT USING XT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.
    DATA: XS_FIELDCAT TYPE SLIS_FIELDCAT_ALV.
    CALL FUNCTION 'REUSE_ALV_FIELDCATALOG_MERGE'
      EXPORTING
        I_PROGRAM_NAME = G_REPID
        I_INTERNAL_TABNAME = 'GT_OUTTAB'
        I_STRUCTURE_NAME = 'ZGER_011_HOME09_1'
        "I_BYPASSING_BUFFER = 'X'
      CHANGING
        CT_FIELDCAT = XT_FIELDCAT.
    LOOP AT XT_FIELDCAT INTO XS_FIELDCAT.
      CASE XS_FIELDCAT-FIELDNAME.
        WHEN 'COLOR'.
        XS_FIELDCAT-tech = 'X'.
        MODIFY XT_FIELDCAT FROM XS_FIELDCAT INDEX sy-tabix.

        WHEN 'VKORG_NR'.


"      IF LS_FIELDCAT-fieldname = 'MAKTX'.
"        LS_FIELDCAT-seltext_s = 'Megn.'.
"        LS_FIELDCAT-seltext_m = 'Megnevezés'.
"        LS_FIELDCAT-seltext_l = 'Anyag megnevezése'.
"        LS_FIELDCAT-reptext_ddic = 'Anyag megnevezése'.
"        MODIFY RT_FIELDCAT FROM LS_FIELDCAT INDEX sy-tabix TRANSPORTING seltext_s reptext_ddic.
"      ELSEIF LS_FIELDCAT-fieldname = 'MATNR'.
"        LS_FIELDCAT-seltext_s = 'Anyag.'.
"        LS_FIELDCAT-seltext_m = 'Anyag.'.
"        LS_FIELDCAT-seltext_l = 'Anyag.'.
"        LS_FIELDCAT-reptext_ddic = 'Anyag.'.
"        IF P_COLORC EQ 'X'.
"          LS_FIELDCAT-emphasize = 'C410'.
"        ENDIF.
"        MODIFY RT_FIELDCAT FROM LS_FIELDCAT INDEX sy-tabix .
"      ELSEIF LS_FIELDCAT-fieldname = 'SPRAS'.
"        LS_FIELDCAT-seltext_s = 'Nyelv'.
"        LS_FIELDCAT-seltext_m = 'Nyelv'.
"        LS_FIELDCAT-seltext_l = 'Nyelv'.
"        LS_FIELDCAT-reptext_ddic = 'Nyelv'.
"        LS_FIELDCAT-tech = p_rejt.
"        MODIFY RT_FIELDCAT FROM LS_FIELDCAT INDEX sy-tabix .
"      ELSEIF LS_FIELDCAT-fieldname = 'IKON'.
"        LS_FIELDCAT-seltext_s = 'Ikon'.
"        LS_FIELDCAT-seltext_m = 'Ikon'.
"        LS_FIELDCAT-seltext_l = 'Ikon'.
"        LS_FIELDCAT-reptext_ddic = 'Ikon'.
"        LS_FIELDCAT-icon = p_ikon.
"        MODIFY RT_FIELDCAT FROM LS_FIELDCAT INDEX sy-tabix .
"      ELSEIF LS_FIELDCAT-fieldname = 'COLOR'.
"        LS_FIELDCAT-tech = 'X'.
"        MODIFY RT_FIELDCAT FROM LS_FIELDCAT INDEX sy-tabix .
"      ELSEIF LS_FIELDCAT-fieldname = 'KESZLET'.
"        LS_FIELDCAT-edit = 'X'.
"        MODIFY RT_FIELDCAT FROM LS_FIELDCAT INDEX sy-tabix .
"      ENDIF.
      ENDCASE.
    ENDLOOP.
ENDFORM.   "FIELDCAT_INIT

*FORM USER_COMMAND USING R_UCOMM LIKE SY-UCOMM
*                        RS_SELFIELD TYPE SLIS_SELFIELD.
*  CASE R_UCOMM.
*    WHEN '&IC1'.  "duplaklikk
*      IF RS_SELFIELD-FIELDNAME EQ 'MATNR'.
*      READ TABLE GT_OUTTAB INTO LS_OUTTAB INDEX RS_SELFIELD-TABINDEX.
*      IF SY-SUBRC = 0.
*        DATA: XT_POPUP TYPE TABLE OF ZGER_STRUCT_KESZLET,
*              XS_POPUP TYPE ZGER_STRUCT_KESZLET.
*
*        SELECT MATNR WERKS LABST INSME SPEME
*        INTO TABLE XT_POPUP
*        FROM MARD
*        WHERE MATNR = LS_OUTTAB-MATNR.
*
*        " Készlet számítása a pop-up táblához
*        LOOP AT XT_POPUP INTO XS_POPUP.
*          XS_POPUP-KESZLET = XS_POPUP-LABST + XS_POPUP-INSME + XS_POPUP-SPEME.
*          MODIFY XT_POPUP FROM XS_POPUP TRANSPORTING KESZLET.
*        ENDLOOP.
*
*          CALL FUNCTION 'REUSE_ALV_POPUP_TO_SELECT'
*            EXPORTING
*              I_TITLE = 'POP-UP'
*              I_ZEBRA = 'X'
*              I_TABNAME = 'LT_POPUP'
*              I_STRUCTURE_NAME = 'ZGER_STRUCT_KESZLET'
*            TABLES
*              T_OUTTAB = XT_POPUP.
*      ENDIF.
*      CLEAR R_UCOMM.
*      ENDIF.
*  ENDCASE.
*ENDFORM.


FORM FETCH_DATA_KNA1_T005T USING XT_OUTTAB TYPE STANDARD TABLE.
  DATA XS_OUTTAB TYPE ZGER_011_HOME09_1 .

  SELECT KNA1~KUNNR KNA1~LAND1 T005T~LANDX KNA1~NAME1 KNA1~NAME2 KNA1~ORT01
         KNA1~PSTLZ KNA1~REGIO KNA1~STRAS KNA1~TELF1
  INTO (XS_OUTTAB-KUNNR, XS_OUTTAB-LAND1, XS_OUTTAB-LANDX, XS_OUTTAB-NAME1, XS_OUTTAB-NAME2, XS_OUTTAB-ORT01, XS_OUTTAB-PSTLZ, XS_OUTTAB-REGIO, XS_OUTTAB-STRAS, XS_OUTTAB-TELF1)
  FROM KNA1
  INNER JOIN T005T ON KNA1~LAND1 = T005T~LAND1
  WHERE KNA1~LAND1 = P_LAND1
    AND T005T~SPRAS = 'H'
    AND KNA1~KUNNR IN SO_KUNNR
    AND KNA1~NAME1 IN SO_NAME1
    AND KNA1~PSTLZ IN SO_PSTLZ.
  APPEND XS_OUTTAB TO XT_OUTTAB.

  ENDSELECT.
ENDFORM. "FETCH_DATA_KNA1_T005T

FORM FETCH_DATA_KNA1_KNVV USING XT_OUTTAB2 TYPE STANDARD TABLE.
  DATA XS_OUTTAB2 TYPE ZGER_011_HOME09_2.
  SELECT KNVV~KUNNR KNA1~NAME1 KNVV~VKORG KNVV~VTWEG KNVV~SPART
  INTO (XS_OUTTAB2-KUNNR, XS_OUTTAB2-NAME1, XS_OUTTAB2-VKORG, XS_OUTTAB2-VTWEG, XS_OUTTAB2-SPART)
  FROM KNVV
  INNER JOIN KNA1 ON KNVV~KUNNR = KNA1~KUNNR
  "itt lehet, hogy a szűrésnél kéne a kunnr intervallum, nem? dehogynem!
  WHERE KNA1~LAND1 = P_LAND1
    AND KNVV~VKORG IN SO_VKORG
    AND KNVV~KUNNR IN SO_KUNNR.
  APPEND XS_OUTTAB2 TO XT_OUTTAB2.
  ENDSELECT.
ENDFORM. "FETCH_DATA_KNA1_KNVV

FORM CALCULATE_VEVO_NR USING XT_OUTTAB TYPE STANDARD TABLE.
  DATA XS_OUTTAB TYPE ZGER_011_HOME09_1.
  LOOP AT XT_OUTTAB INTO XS_OUTTAB.
    XS_OUTTAB-VEVO_NR = 1.
    MODIFY XT_OUTTAB FROM XS_OUTTAB.
  ENDLOOP.
ENDFORM. "CALCULATE_VEVO_NR

FORM CALCULATE_VKORG_NR.
  DATA: LV_COUNT TYPE I.

  LOOP AT GT_OUTTAB INTO LS_OUTTAB.
    LV_COUNT = 0.
    LOOP AT GT_OUTTAB2 INTO LS_OUTTAB2 WHERE KUNNR = LS_OUTTAB-KUNNR.
      LV_COUNT = LV_COUNT + 1.
    ENDLOOP.
    LS_OUTTAB-VKORG_NR = LV_COUNT.


    " Színezési logika a VKORG_NR mezőhöz
    IF LV_COUNT = 2.
      LS_OUTTAB-COLOR = 'C310'. " Sárga
    ELSEIF LV_COUNT = 3.
      LS_OUTTAB-COLOR = 'C410'. " Kék
    ELSEIF LV_COUNT > 3.
      LS_OUTTAB-COLOR = 'C710'. " Narancssárga
    ENDIF.

    MODIFY GT_OUTTAB FROM LS_OUTTAB.
  ENDLOOP.
ENDFORM. "CALCULATE_VKORG_NR